apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # "rootpassword" encodé en base64
  # Pour changer : echo -n 'tonmotdepasse' | base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
